3- class classification( k = 15, weights = 'uniform')  
k : should be odd, 15 nearest points of one selected point  
uniform : give equal importance for all data points  
distance : give greater importance for clower data points  


In [10]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics, svm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from matplotlib import pyplot as plt

data = pd.read_csv('car.data')
print(data.head())

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


There is no title for the columns  
So editing the csv file by putting at the titles at the first rwo.

In [11]:
X = data[['buying', 'maint', 'safety']].values
y = data[['class']]
X = np.array(X)
print(X,y)

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]


In [12]:
# Converting data
# X
Le = LabelEncoder() 
# as the data is string to put in ML Algorithm it should be number
for i in range(len(X[0])):
    X[:, i] = Le.fit_transform(X[:, i])
print(X)
# Another way of conversion
# y
label_mapping = {
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}
y['class'] = y['class'].map(label_mapping)
y = np.array(y)
print(y)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]
[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()


In [13]:
# create model
knn = neighbors.KNeighborsClassifier(n_neighbors=25,weights='uniform')

# need to train
# for the training : need to separate test and train data
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.2)
knn.fit(X_train, y_train)
prediction = knn.predict(X_test)
accuracy = metrics.accuracy_score(y_test, prediction)
print("predictions:", prediction)
print("accuracy: ", accuracy)

a = 1727
print("actual value ", y[a])
print("predicted value", knn.predict(X)[a])

#knn = svm.SVC()

predictions: [0 2 3 1 1 3 1 1 1 0 3 0 0 0 2 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 0
 1 0 0 0 0 0 1 0 0 2 1 0 0 0 3 1 1 0 0 0 0 3 0 0 0 1 0 0 0 0 0 0 2 0 1 0 0
 2 1 0 0 0 0 1 0 0 0 0 0 0 1 2 0 0 0 0 0 2 2 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1
 0 1 0 1 3 0 3 0 0 0 0 0 1 1 0 0 0 2 0 3 0 1 3 0 0 3 0 1 0 1 1 0 0 3 0 0 1
 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 2 0 1 1 1 0 0 0 2 0 0 1 0 0 0 1 0
 0 0 3 3 0 2 0 0 3 1 1 0 1 1 0 0 3 3 0 0 1 0 1 0 0 0 0 0 0 1 0 0 2 0 2 0 0
 1 1 2 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 2 1 0 1 1 0 0 0 0 0 1 1 1 0 1 0 0
 0 0 0 0 0 0 0 3 0 1 0 1 0 2 0 2 0 0 1 0 1 1 0 1 1 0 0 3 0 0 2 0 1 0 1 0 0
 1 1 3 3 0 1 2 3 0 0 0 1 1 1 0 0 2 0 0 1 0 0 0 0 1 0 3 3 3 1 1 0 0 1 0 0 2
 1 0 1 0 2 3 0 0 1 2 0 3 1]
accuracy:  0.7427745664739884
actual value  [3]
predicted value 3


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  import sys
